// Product catalog for P Santhosh Electronics.
// Each product's `model` field selects a procedural 3D representation
// (see components/models/ProjectModels.js) and `accent` tints that model
// and its badges. Update freely as the real catalog grows.

export const PRODUCTS = [
  // ---------- BASIC ----------
  {
    id: 'led-chaser-circuit',
    partNumber: 'SE-LC01',
    name: 'LED Chaser Light Circuit',
    subtitle: '555 Timer IC Project',
    tagline: 'Sequential LED chase lighting built around a single 555 timer IC.',
    description:
      'A classic first solder project. A 555 timer generates clock pulses that drive a CD4017 decade counter, lighting 10 LEDs one after another to create a chasing effect. Great for learning timing circuits before moving to microcontrollers.',
    level: 'basic',
    price: 449,
    model: 'circuit-board',
    accent: '#D99A2B',
    buildTime: '45–60 min',
    skills: ['555 timer ICs', 'RC timing circuits', 'Through-hole soldering'],
    kit: [
      '555 Timer IC + CD4017 counter IC',
      '10 × 5mm LEDs (mixed colours)',
      'Resistor & capacitor set',
      'Pre-drilled PCB',
      '9V battery clip',
      'Step-by-step build sheet',
    ],
  },
  {
    id: 'fm-radio-receiver-kit',
    partNumber: 'SE-FM02',
    name: 'Simple FM Radio Receiver',
    subtitle: 'TDA7088 Mono Receiver',
    tagline: 'Tune into local FM stations on a compact hand-built receiver.',
    description:
      'Built around the TDA7088 FM IC, this kit walks you through winding your own tuning coil and assembling a working mono FM receiver with speaker output. A gentle, satisfying introduction to RF circuits.',
    level: 'basic',
    price: 599,
    model: 'circuit-board',
    accent: '#2F8FA6',
    buildTime: '60–75 min',
    skills: ['RF tuning basics', 'Coil winding', 'Audio output stages'],
    kit: [
      'TDA7088 FM receiver IC',
      'Tuning capacitor & coil wire',
      'Mini speaker + 3.5mm jack',
      'PCB & antenna wire',
      'Battery holder (2×AA)',
      'Build sheet with tuning guide',
    ],
  },
  {
    id: 'automatic-night-lamp',
    partNumber: 'SE-NL03',
    name: 'Automatic Night Lamp',
    subtitle: 'LDR Light-Sensing Switch',
    tagline: 'Switches your lamp on the moment the room goes dark.',
    description:
      'A light-dependent resistor (LDR) monitors ambient brightness and drives a transistor switch that energises a relay, turning a connected lamp on at dusk and off at dawn. No microcontroller needed.',
    level: 'basic',
    price: 399,
    model: 'circuit-board',
    accent: '#E0B84B',
    buildTime: '30–45 min',
    skills: ['LDR sensors', 'Transistor switching', 'Relay driving'],
    kit: [
      'LDR sensor + BC547 transistor',
      '5V relay module',
      'Indicator LEDs',
      'Resistor set',
      'Pre-drilled PCB',
      'Screw terminal block',
    ],
  },
  {
    id: 'water-level-indicator',
    partNumber: 'SE-WL04',
    name: 'Water Level Indicator & Alarm',
    subtitle: '5-Stage Tank Monitor',
    tagline: 'Sounds a buzzer before your overhead tank overflows.',
    description:
      'Five probe wires sense rising water level in a tank and light a matching row of LEDs, with a buzzer that sounds once the tank is full. A practical, everyday-useful transistor-array project.',
    level: 'basic',
    price: 499,
    model: 'circuit-board',
    accent: '#2F8FA6',
    buildTime: '45 min',
    skills: ['Transistor arrays', 'Water-level sensing', 'Buzzer circuits'],
    kit: [
      'BC547 transistor array (5-stage)',
      'Piezo buzzer',
      '5 × sensor probe wires',
      '5 × indicator LEDs',
      'Pre-drilled PCB',
      '9V battery clip',
    ],
  },
  {
    id: 'mini-solar-mobile-charger',
    partNumber: 'SE-SC05',
    name: 'Mini Solar Mobile Charger',
    subtitle: 'Pocket Solar Power Bank',
    tagline: 'Charge a phone from sunlight with a pocket-sized panel.',
    description:
      'A small 6V solar panel tops up an 18650 Li-ion cell through a TP4056 charge controller, and a boost converter steps the output up to a stable 5V USB output. Doubles as an introduction to safe battery charging.',
    level: 'basic',
    price: 699,
    model: 'solar-panel',
    accent: '#2F8FA6',
    buildTime: '40 min',
    skills: ['Solar charging', 'Li-ion battery care', 'Boost converters'],
    kit: [
      '6V / 3W solar panel',
      'TP4056 charging module',
      '18650 cell + holder',
      '5V boost converter (USB out)',
      'Compact enclosure',
      'Assembly guide',
    ],
  },
  {
    id: 'handheld-metal-detector',
    partNumber: 'SE-MD06',
    name: 'Handheld Metal Detector',
    subtitle: 'Beat-Frequency Coil Detector',
    tagline: 'Detects coins and buried metal with a beat-frequency coil.',
    description:
      'Two oscillators tuned to nearly the same frequency create an audible beat note that shifts when the search coil passes near metal. Includes coil-winding practice and a telescopic handle for a genuinely usable detector.',
    level: 'basic',
    price: 899,
    model: 'handheld-detector',
    accent: '#B8722E',
    buildTime: '90 min',
    skills: ['Oscillator circuits', 'Coil winding', 'Beat-frequency detection'],
    kit: [
      'Search coil + winding wire',
      'Dual-oscillator PCB',
      'Piezo buzzer + LED indicator',
      'Telescopic handle & grip',
      '9V battery clip',
      'Tuning instructions',
    ],
  },

  // ---------- INTERMEDIATE ----------
  {
    id: 'line-follower-robot',
    partNumber: 'SE-LF07',
    name: 'IR Line Follower Robot',
    subtitle: '2-Motor Autonomous Bot',
    tagline: 'Follows a black line on the floor using IR reflectance sensors.',
    description:
      'Twin IR sensors read the contrast between a black line and the floor, and an Arduino Nano steers two geared motors through an L298N driver to stay on track. A hands-on introduction to closed-loop control.',
    level: 'intermediate',
    price: 1599,
    model: 'robot',
    accent: '#1B5E3A',
    buildTime: '2–3 hrs',
    skills: ['IR sensor arrays', 'Motor driving', 'Basic closed-loop control'],
    kit: [
      'Arduino Nano (pre-flashed)',
      '2 × IR reflectance sensors',
      'L298N motor driver',
      '2 × BO motors + wheels',
      'Chassis + castor wheel',
      'Battery holder & wiring',
    ],
  },
  {
    id: 'obstacle-avoiding-robot',
    partNumber: 'SE-OA08',
    name: 'Ultrasonic Obstacle Avoiding Robot',
    subtitle: 'HC-SR04 Sensing Bot',
    tagline: 'Navigates around obstacles using ultrasonic ranging.',
    description:
      'An HC-SR04 ultrasonic sensor mounted on a servo sweeps the space ahead, and the Arduino Nano steers away from anything closer than a set distance. Extendable with your own avoidance logic.',
    level: 'intermediate',
    price: 1499,
    model: 'robot',
    accent: '#B8722E',
    buildTime: '2–3 hrs',
    skills: ['Ultrasonic ranging', 'Servo sweep scanning', 'Arduino programming'],
    kit: [
      'Arduino Nano (pre-flashed)',
      'HC-SR04 ultrasonic sensor + servo mount',
      'L298N motor driver',
      '2 × BO motors + wheels',
      'Chassis + castor wheel',
      'Battery pack & wiring',
    ],
  },
  {
    id: 'dtmf-robot-car',
    partNumber: 'SE-DT09',
    name: 'DTMF Mobile Controlled Robot Car',
    subtitle: 'Call-Controlled 4WD',
    tagline: 'Drive the car by pressing phone keys during a call — no app needed.',
    description:
      'A second phone stays permanently in a call with one mounted on the robot. A DTMF decoder reads the key tones you press and an Arduino translates them into drive commands — forward, reverse, left, right.',
    level: 'intermediate',
    price: 1999,
    model: 'robot',
    accent: '#2F8FA6',
    buildTime: '2.5–3 hrs',
    skills: ['DTMF decoding', 'Remote control logic', '4WD chassis assembly'],
    kit: [
      'Arduino Nano (pre-flashed)',
      'DTMF decoder module',
      'L298N motor driver',
      '4 × BO motors + wheels',
      '4WD chassis',
      'Battery holder & wiring',
    ],
  },
  {
    id: 'bluetooth-home-automation-kit',
    partNumber: 'SE-HA10',
    name: 'Arduino Bluetooth Home Automation Kit',
    subtitle: '4-Channel Relay + App Control',
    tagline: 'Control 4 home appliances from your phone over Bluetooth.',
    description:
      'An HC-05 Bluetooth module pairs with a phone app to switch a 4-channel relay board, letting you turn real household appliances on and off from across the room. A practical, immediately useful build.',
    level: 'intermediate',
    price: 1899,
    model: 'circuit-board',
    accent: '#2F8FA6',
    buildTime: '2 hrs',
    skills: ['Bluetooth serial comms', 'Relay switching', 'App-to-hardware control'],
    kit: [
      'Arduino Uno (pre-flashed)',
      'HC-05 Bluetooth module',
      '4-channel relay board',
      'Control app link (Android)',
      'Enclosure + terminal blocks',
      'Wiring & safety guide',
    ],
  },
  {
    id: 'gsm-home-security-alarm',
    partNumber: 'SE-GS11',
    name: 'GSM Home Security Alarm',
    subtitle: 'SMS Intrusion Alert System',
    tagline: 'Sends an SMS the moment a door or window opens.',
    description:
      'A door reed switch and PIR sensor feed into an Arduino Uno, which triggers a SIM800L GSM module to send an SMS alert and sound a local buzzer the instant a breach is detected. Runs on any 2G SIM.',
    level: 'intermediate',
    price: 2299,
    model: 'circuit-board',
    accent: '#C1442E',
    buildTime: '2.5 hrs',
    skills: ['GSM/SIM communication', 'Interrupt-driven sensing', 'Alert system design'],
    kit: [
      'Arduino Uno (pre-flashed)',
      'SIM800L GSM module',
      'PIR sensor + door reed switch',
      'Piezo buzzer',
      'Enclosure + SIM slot',
      'Setup & AT-command guide',
    ],
  },
  {
    id: 'iot-weather-station',
    partNumber: 'SE-WS12',
    name: 'IoT Weather Monitoring Station',
    subtitle: 'ESP32 + DHT11, Wi-Fi Connected',
    tagline: 'Streams live temperature and humidity to a web dashboard.',
    description:
      'An ESP32 reads temperature and humidity from a DHT11 sensor and posts it to a live web dashboard over Wi-Fi, with an OLED screen for an at-a-glance local readout. A first step into the IoT.',
    level: 'intermediate',
    price: 2499,
    model: 'weather-station',
    accent: '#2F8FA6',
    buildTime: '2 hrs',
    skills: ['Wi-Fi microcontrollers', 'Sensor calibration', 'Cloud dashboards'],
    kit: [
      'ESP32 dev board (pre-flashed)',
      'DHT11 temperature/humidity sensor',
      '0.96" OLED display',
      'Weatherproof enclosure',
      'Mounting bracket',
      'Dashboard setup guide',
    ],
  },
  {
    id: 'biometric-fingerprint-lock',
    partNumber: 'SE-BL13',
    name: 'Biometric Fingerprint Door Lock',
    subtitle: 'R307 Sensor + Solenoid Strike',
    tagline: 'Unlocks a door solenoid only for enrolled fingerprints.',
    description:
      'An R307 optical fingerprint sensor stores enrolled prints on an Arduino Nano, driving a relay-controlled 12V solenoid lock only on a match. Includes a keypad override for backup access.',
    level: 'intermediate',
    price: 2799,
    model: 'security-lock',
    accent: '#1B5E3A',
    buildTime: '2.5–3 hrs',
    skills: ['Biometric sensor interfacing', 'Access-control logic', 'Solenoid actuation'],
    kit: [
      'Arduino Nano (pre-flashed)',
      'R307 fingerprint sensor',
      '12V solenoid lock + relay driver',
      '4×3 keypad override',
      'Enclosure + mounting plate',
      'Enrolment & wiring guide',
    ],
  },
];

export function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(product, count = 3) {
  return PRODUCTS.filter((p) => p.id !== product.id && p.level === product.level).slice(0, count);
}
